
version: "3.9"
services:
  bind:
    image: sameersbn/bind:latest
    dns: 127.0.0.1
    environment:
      - ROOT_PASSWORD=SecretPassword
    ports:
    - 10000:10000
    - 53:53/udp
    volumes:
      - /srv/docker/bind:/data
networks:
  frontend:
    name: app-builder_default
    driver: bridge
