version: "3.5"
services:
  coder:
    image: docker.io/codercom/coder:1.33.3
    container_name: coderd
    restart: unless-stopped
    ports:
      - 80:7080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.coder:/var/run/coder
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
